services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-persistence:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@personal.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-persistence:/var/lib/pgadmin
    networks:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8083"
    networks:
      - spring
    depends_on:
      - zipkin

  washing-machine:
    image: washing-machine-app:latest
    container_name: washing-machine
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres

  product:
    image: product:latest
    container_name: product
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres

#  TODO: setup solar panel
#  solar-panel:
#    image: solar-panel:latest
#    container_name: solar-panel
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - "8084:8084"
#    networks:
#      - spring
#      - postgres
#    depends_on:
#      - zipkin
#      - postgres

networks:
  postgres:
    driver: bridge

  spring:
    driver: bridge

volumes:
  postgres-persistence:
  pgadmin-persistence: