spring:
  cloud:
    gateway:
      routes:
        #TODO: Add proper security
        - id: washing-machine
          uri: http://hephaestus-washing-machine:8080
          predicates:
            - Path=/v1/washing-machines/**, /api/v1/users/**, /v3/api-docs/washing-machine
          filters:
            - RewritePath=/v3/api-docs/washing-machine, /v3/api-docs  # Forward to actual OpenAPI docs path

        - id: solar-panel
          uri: http://hephaestus-solar-panel:8084
          predicates:
            - Path=/v1/solar-panels/**, /v3/api-docs/solar-panel
          filters:
            - RewritePath=/v3/api-docs/solar-panel, /v3/api-docs  # Forward to actual OpenAPI docs path

        - id: product
          uri: http://hephaestus-product:8081
          predicates:
            - Path=/v1/products/**, /v3/api-docs/product
          filters:
            - RewritePath=/v3/api-docs/product, /v3/api-docs  # Forward to actual OpenAPI docs path

management:
  zipkin:
    tracing:
      endpoint: http://hephaestus-zipkin:9411/api/v2/spans