server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411

  cloud:
    gateway:
      routes:
        - id: user
          #TODO: Implement proper security
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/users/**

        - id: washing-machine
          uri: http://washing-machine:8080
          predicates:
            - Path=/api/v1/washing-machines/**

        - id: product
          #TODO: Change this URI to product:8081!
          uri: http://washing-machine:8080
          predicates:
            - Path=/api/v1/products/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG