server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
        #TODO: Add proper security
        - id: washing-machine
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/washing-machines/**, /api/v1/users/**

        - id: product
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG