server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
        - id: washing-machines
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/washing-machines/**

        - id: products
          #TODO: Change this URI to localhost:8081
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/products/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG