server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        #TODO: Add proper security
        - id: washing-machine
          uri: http://washing-machine:8080
          predicates:
            - Path=/api/v1/washing-machines/**, /api/v1/users/**

        - id: product
          uri: http://product:8081
          predicates:
            - Path=/api/v1/products/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    org.springframework.cloud.gateway: DEBUG